.PHONY: test
dict_exercise:
	py.test test/unittests_dict_exercise.py -vv
	py.test --pep8 src/dict_exercise.py
efficiency:
	py.test test/unittests_efficiency.py
	py.test --pep8 src/efficiency.py
substring:
	py.test test/unittests_substring.py
	py.test -- pep8 src/substring.py
